# Generated by Django 2.2.6 on 2020-05-23 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_lesson_studentlessonresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlessonresult',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 23, 19, 18, 24, 355748)),
        ),
    ]
