# Generated by Django 2.2.6 on 2020-05-23 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_studentlessonresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlessonresult',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
