# Generated by Django 2.2.6 on 2020-05-27 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_auto_20200523_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlessonresult',
            name='date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_app.StudentGroup'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group_in_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_app.GroupInStream'),
        ),
    ]
