# Generated by Django 2.2.6 on 2020-06-23 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_auto_20200527_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TaskWithTick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.Section')),
            ],
        ),
        migrations.CreateModel(
            name='TaskWithTickOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('task_with_tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.TaskWithTick')),
            ],
        ),
        migrations.CreateModel(
            name='TaskWithTickStudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perform', models.BooleanField(default=False)),
                ('task_with_tick_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.TaskWithTickOption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
