# Generated by Django 2.2.6 on 2020-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_auto_20200605_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='check',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='check',
            name='mark',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
